server:
  port: 80

spring:
  application:
    name: cloud-order-server

eureka:
  client:
    register-with-eureka: true #表示是否向eureka注册自己
    service-url: # 简单理解为监控页面的地址
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true
